### ISSUE TITLE
can you provide an example about integrating actix-web? 

### ISSUE THREAD

**Issue by vidyli** [XAMPPRocky/fluent-templates#28]
this uses unic-langid, actix-web uses lantag, currently I need to convert LanguageIdentifier to langtag, which is very cumbersome

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However I don't think this is an issue with `fluent-templates`. The issue is more with the `language-tags` or `unic-langid` crates. The best solution would be for one of those crates to provide a `From` or `TryFrom` implementation for one or the other, then you'd be able to easily convert between the two types.

**Comment by vidyli** [comment]
@XAMPPRocky  thanks for you quick response, I found a easy way, simply turn Vec<LanguageIdentifier> into string

**Comment by XAMPPRocky** [comment]
I mean, it might still be worth opening an issue with one of the crates, so that the conversion is part of the type system and not "stringly" typed.

**Comment by zbraniecki** [comment]
my hope is that we're all going to converge on icu4x_locid soon.
